'use client'
import { createContext, useContext, useState, useEffect } from 'react'

export type AdminLang = 'en' | 'es'

// ── Translations ──────────────────────────────────────────────────────────────
export const ADMIN_TRANSLATIONS: Record<AdminLang, Record<string, string>> = {
  en: {
    // Sidebar / Shell
    nav_dashboard: 'Dashboard',
    nav_volunteers: 'Volunteers',
    nav_shifts: 'Shifts',
    nav_documents: 'Documents',
    nav_reports: 'Reports',
    nav_messages: 'Messages',
    nav_alerts: 'Alerts',
    nav_settings: 'Settings',
    nav_learning: 'Learning',
    sign_out: 'Sign out',
    admin_portal: 'Admin Portal',
    language: 'Language',

    // Volunteers list
    volunteers_title: 'Volunteers',
    add_volunteer: 'Add Volunteer',
    search_placeholder: 'Search by name or email…',
    filter_status: 'Filter by status',
    filter_category: 'Filter by category',
    all_statuses: 'All statuses',
    all_categories: 'All categories',
    all_locations: 'All locations',
    col_name: 'Volunteer',
    col_status: 'Status',
    col_category: 'Category',
    col_pipeline: 'Pipeline',
    col_tags: 'Tags',
    col_flags: 'Flags',
    col_locations: 'Location(s)',
    col_hours: 'Hrs / mo',
    col_actions: 'Actions',
    no_volunteers: 'No volunteers found',
    no_volunteers_sub: 'Try adjusting your search or filters.',
    status_volunteer: 'Volunteer',
    status_prospect: 'Prospect',
    status_applicant: 'Applicant',
    status_inactive: 'Inactive',
    clear: 'Clear',
    result: 'result',
    results: 'results',
    this_mo: 'this mo.',

    // Add volunteer modal
    add_volunteer_title: 'Add Volunteer',
    add_volunteer_sub: 'Creates an account and volunteer profile',
    first_name_required: 'First name *',
    last_name_required: 'Last name *',
    email_address_required: 'Email address *',
    phone_optional: 'Phone',
    optional: 'optional',
    category_required: 'Category *',
    status_required: 'Status *',
    assign_locations: 'Assign to location(s)',
    send_invite_email: 'Send invite email',
    send_invite_desc: 'Volunteer receives a link to set their own password. Uncheck to create the account silently (you\'ll need to share credentials manually).',
    volunteer_added: 'Volunteer added!',
    invite_sent: 'An invite email has been sent.',
    account_created: 'Account created successfully.',
    creating: 'Creating…',
    done: '✓ Done',
    cancel: 'Cancel',

    // Volunteer detail — header
    back_to_volunteers: 'Back to Volunteers',
    total_hours_label: 'Total Hours',
    credentials_label: 'Credentials',
    lessons_done_label: 'Lessons Done',
    joined: 'Joined',

    // Volunteer detail — tabs
    tab_info: 'Info',
    tab_onboarding: 'Onboarding',
    tab_credentials: 'Credentials',
    tab_hours: 'Hours',
    tab_documents: 'Documents',
    tab_background_check: 'Background Check',
    tab_flags: 'Flags',
    tab_notes: 'Notes',

    // InfoTab
    volunteer_details: 'Volunteer Details',
    edit: 'Edit',
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Saved',
    first_name: 'First Name',
    last_name: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    status_field: 'Status',
    emergency_contact: 'Emergency Contact',
    emergency_phone: 'Emergency Phone',
    managed_via_pipeline: 'Managed via Pipeline tab',
    set_by_volunteer: 'Set by volunteer',
    category: 'Category',
    categories: 'Categories',
    select_all_that_apply: 'select all that apply',
    locations_field: 'Location(s)',

    // Tags
    tags_label: 'Tags',
    add_tag: '+ Add tag',
    no_tags_defined: 'No tags defined yet.',
    create_tags_in_settings: 'Create tags in Settings →',
    no_tags_applied: 'No tags applied.',

    // Notes panel
    add_note_placeholder: 'Add a note…',
    add_note_btn: 'Add note',
    no_notes: 'No notes yet.',
    saving_note: 'Saving…',

    // Documents panel
    upload_document: 'Upload Document',
    drop_files_here: 'Drop files here, or',
    browse: 'browse',
    drop_files_sub: 'PDF, Word, Excel, PNG, JPG — up to 50 MB each',
    uploaded_files: 'Uploaded Files',
    signed_documents: 'Signed Documents',
    supporting_documents: 'Supporting Documents',
    no_documents: 'No documents on file — upload one above',
    send_via_jotform: 'Send via Jotform',
    form_id: 'Form ID',
    send_form: 'Send Form',
    sending: 'Sending…',
    form_sent: 'Form sent!',
    open: 'Open',

    // Flags panel
    active_flags: 'Active Flags',
    raise_flag: 'Raise flag',
    no_active_flags: 'No active flags.',
    no_flag_types: 'No flag types defined yet.',
    create_flags_in_settings: 'Create flags in Settings →',
    select_flag_type: 'Select a flag type',
    optional_notes: 'Optional notes about this flag…',
    raise_flag_btn: 'Raise flag',
    resolve: 'Resolve',
    unresolve: 'Unresolve',
    hide: 'Hide',
    show: 'Show',
    resolved: 'resolved',
    flag: 'flag',
    flags: 'flags',
    raised: 'Raised',

    // Pipeline phase bar
    pipeline_phase: 'Pipeline Phase',
    override: 'Override',
    advance_to: 'Advance to',
    final_phase: 'Final phase',

    // Clock in button
    clock_in: 'Clock In',
    clock_out: 'Clock Out',
    clocking_in: 'Clocking in…',
    clocking_out: 'Clocking out…',
    clocked_in: 'Clocked in',

    // Onboarding tab
    onboarding_checklist: 'Onboarding Checklist',
    complete: 'complete',
    workflow_stages: 'Workflow Stages',
    stages: 'stages',
    mark_done: 'Mark done',
    done_label: 'Done',
    pending_label: 'Pending',
    no_workflow: 'No onboarding workflow assigned to this volunteer.',
    completed: 'Completed',
    due_within: 'Due within',
    days_of_start: 'days of start',

    // Credentials tab
    no_credentials: 'No credentials on file',
    license: 'License:',
    expires: 'Expires',
    expired: 'Expired',
    verified: '✓ Verified',
    days_left: 'd left',

    // Hours tab
    total_hours: 'Total Hours',
    sessions: 'Sessions',
    avg_session: 'Avg Session',
    no_time_entries: 'No time entries yet',
    date: 'Date',
    location: 'Location',
    clock_in_col: 'Clock In',
    clock_out_col: 'Clock Out',
    duration: 'Duration',
    method: 'Method',
    active_label: 'Active',

    // Background check tab
    no_bg_check: 'No background check initiated',
    initiate_bg_check: 'Initiate Background Check',
    provider: 'Provider',
    bg_status: 'Status',
    initiated: 'Initiated',
    bg_completed: 'Completed',
    bg_result: 'Result',

    // Shifts
    shifts_title: 'Shifts',
    new_shift: 'New Shift',
    no_shifts: 'No shifts',
    shift_date: 'Date',
    shift_time: 'Time',
    shift_location: 'Location',
    shift_volunteer: 'Volunteer',
    shift_status: 'Status',
    week_view: 'Week',
    day_view: 'Day',
    list_view: 'List',
    month_view: 'Month',
    today: 'Today',
    upcoming: 'Upcoming',
    past: 'Past',
    shift_name: 'Shift Name',
    start_date: 'Start Date',
    start_time: 'Start Time',
    end_date: 'End Date',
    end_date_occurrence: 'Each Shift Ends On',
    end_time: 'End Time',
    end_time_occurrence: 'Each Shift Ends At',
    required_volunteers: 'Required Volunteers',
    shift_notes: 'Notes',
    assign_volunteers: 'Assign Volunteers',
    assign_btn: 'Assign',
    create_shift: 'Create Shift',
    delete_shift: 'Delete shift',
    edit_shift: 'Edit',
    recurring_shift: 'Recurring Shift',
    repeat_frequency: 'Repeat',
    end_date_optional: 'Series end date (optional)',
    series_end_date_hint: 'Leave blank to repeat indefinitely',
    weekly: 'Weekly',
    biweekly: 'Bi-weekly',
    monthly: 'Monthly',
    spots_open: 'spots open',
    spot_open: 'spot open',
    no_shifts_this_day: 'No shifts this day.',
    no_results: 'No results',
    search_volunteers: 'Search volunteers…',
    select_mentor: 'Select a mentor for',
    trainee_label: 'Trainee',
    no_eligible_mentors: 'No eligible mentors found.',

    // Edit recurring modal
    edit_recurring_title: 'Edit recurring shift',
    this_shift_only: 'This shift only',
    this_shift_only_desc: 'Only the selected occurrence will be updated.',
    this_and_future: 'This and all future shifts',
    this_and_future_desc: 'This and all occurrences after it will be updated.',
    confirm: 'Confirm',

    // Documents view
    documents_title: 'Documents',
    no_documents_found: 'No documents found',
    preset_docs: 'Standard Forms',
    volunteer_repo: 'Volunteer Repository',
    internal_docs: 'Internal Documents',
    upload_file: 'Upload file',
    hidden: 'Hidden',
    visible: 'Visible',
    preset: 'Preset',
    internal: 'Internal',
    standard_form: 'Standard form · Always visible to volunteers',

    // Reports
    reports_title: 'Reports',
    total_volunteers: 'Total Volunteers',
    total_hours_report: 'Total Hours',
    active_volunteers: 'Active Volunteers',
    hours_this_month: 'Hours This Month',
    hours_tab: 'Hours',
    onboarding_tab: 'Onboarding',
    bgchecks_tab: 'Background Checks',
    credentials_tab: 'Credential Expiry',
    inactive_tab: 'Inactive',
    filters: 'Filters',
    apply: 'Apply',
    status_filter: 'Status',
    category_filter: 'Category',
    pipeline_phase_filter: 'Pipeline Phase',
    joined_from: 'Joined From',
    joined_to: 'Joined To',
    all: 'All',
    export_csv: 'Export CSV',
    mark_inactive: 'Mark Inactive',
    approve: 'Approve',
    reject: 'Reject',
    color: 'Color',
    add_tag_btn: 'Add tag',
    pending_hour_approvals: 'Pending Hour Approvals',
    no_pending_hours: 'No pending hours to review.',
    volunteer: 'Volunteer',
    shift_hours: 'Hours',
    sessions_col: 'Sessions',
    distribution_col: 'Distribution',
    no_hours_found: 'No hours data found',
    all_phases: 'All phases',
    no_volunteers_filter: 'No volunteers match the current filter',
    phase_col: 'Phase',
    workflow_col: 'Workflow',
    stages_col: 'Stages',
    progress_col: 'Progress',
    no_workflow_assigned: 'No workflow',
    no_bgcheck_data: 'No background check data yet',
    custom_days: 'Custom',
    set_day_threshold: 'Set a day threshold above',
    no_inactive_volunteers: 'No volunteers inactive for',
    name_col: 'Name',
    last_active_col: 'Last Active',
    no_activity_in_last: 'No activity in last:',
    days_suffix: 'days',
    expiring_within: 'Expiring within:',
    no_creds_expiring: 'No credentials expiring in the next',
    days_label: 'days',
    marking_inactive: 'Marking…',
    credential_type_col: 'Credential Type',
    expires_col: 'Expires',
    days_left_col: 'Days Left',
    urgency_col: 'Urgency',
    never_label: 'Never',

    // Messages
    messages_title: 'Messages',
    send_message: 'Send Message',
    message_placeholder: 'Type a message…',
    compose: 'Compose',
    compose_new_message: 'Compose New Message',
    inbox: 'Inbox',
    all_volunteers: 'All Volunteers',
    group_by_category: 'Group by Category',
    individual: 'Individual',
    by_category_label: 'By Category',
    individuals_label: 'Individuals',
    subject: 'Subject',
    body: 'Message',
    send: 'Send',
    sending_msg: 'Sending…',
    send_later: 'Send Later',
    schedule_for: 'Scheduled for',
    scheduled_badge: 'Scheduled',
    cancel_schedule: 'Send Now Instead',
    recipient_count: 'recipient',
    recipient_count_plural: 'recipients',
    save_template: 'Save as Template',
    templates: 'Templates',
    no_messages: 'No messages sent yet.',
    no_messages_hint: 'Compose a message to get started',
    no_templates_yet: 'No templates yet. Compose a message and save it as a template.',
    use_template: 'Use',
    select_template_placeholder: 'Select a template…',
    template_name_label: 'Template name',
    channel_label: 'Channel',
    to_label: 'To',
    channel_email: 'Email',
    channel_sms: 'SMS',
    channel_push: 'Push',
    new_message: 'New Message',
    message_body_label: 'Message Body',
    select_message_view: 'Select a message to view',
    recipients_stat: 'Recipients',
    delivered_stat: 'Delivered',
    read_stat: 'Read',
    sent_prefix: 'Sent',
    save_label: 'Save',

    // Alerts
    alerts_title: 'Alerts',
    no_alerts: 'No alerts yet',
    no_alerts_sub: 'Alerts will appear here when document automation rules are triggered.',
    mark_resolved: 'Mark Resolved',
    mark_all_read: 'Mark all read',
    alert_type: 'Type',
    alert_message: 'Message',
    unread: 'unread',
    view_volunteer: 'View volunteer →',

    // Settings
    settings_title: 'Settings',
    categories_section: 'Categories',
    add_category: 'Add Category',
    category_name: 'Category Name',
    archive: 'Archive',
    restore: 'Restore',
    tags_section: 'Tags',
    flags_section: 'Flags',
    tags_desc: 'Categorical labels applied to volunteers for grouping and filtering.',
    flags_desc: 'Alert-style markers for issues that need attention (e.g. "Reference not called", "License expiring").',
    no_tags_yet: 'No tags yet.',
    no_flags_yet: 'No flags defined yet.',
    tag_name: 'Tag Name',
    create_tag: 'Create Tag',
    flag_name: 'Flag Name',
    flag_description: 'Description (optional)',
    severity: 'Severity',
    severity_info: 'Info',
    severity_warning: 'Warning',
    severity_critical: 'Critical',
    add_flag_btn: 'Add flag',
    create_flag: 'Create Flag',
    org_profile: '🏢 Org Profile',
    locations_tab: '📍 Locations',
    integrations_tab: '🔗 Integrations',
    categories_tab: '🗂 Categories',
    holidays_tab: '📅 Holidays',
    automation_tab: '⚡ Automation',
    tags_tab: '🏷 Tags',
    flags_tab: '🚩 Flags',

    // Learning
    learning_title: 'Learning',
    new_module: 'New Module',
    lessons: 'Lessons',
    completions: 'Completions',
    add_lesson: 'Add Lesson',
    no_modules: 'No modules yet.',
    module_title: 'Module Title',
    lesson_title: 'Lesson Title',
    lesson_type: 'Type',
    save_module: 'Save Module',
  },

  es: {
    // Sidebar / Shell
    nav_dashboard: 'Panel',
    nav_volunteers: 'Voluntarios',
    nav_shifts: 'Turnos',
    nav_documents: 'Documentos',
    nav_reports: 'Informes',
    nav_messages: 'Mensajes',
    nav_alerts: 'Alertas',
    nav_settings: 'Configuración',
    nav_learning: 'Aprendizaje',
    sign_out: 'Cerrar sesión',
    admin_portal: 'Portal Administrativo',
    language: 'Idioma',

    // Volunteers list
    volunteers_title: 'Voluntarios',
    add_volunteer: 'Agregar voluntario',
    search_placeholder: 'Buscar por nombre o correo…',
    filter_status: 'Filtrar por estado',
    filter_category: 'Filtrar por categoría',
    all_statuses: 'Todos los estados',
    all_categories: 'Todas las categorías',
    all_locations: 'Todas las ubicaciones',
    col_name: 'Voluntario',
    col_status: 'Estado',
    col_category: 'Categoría',
    col_pipeline: 'Proceso',
    col_tags: 'Etiquetas',
    col_flags: 'Marcadores',
    col_locations: 'Ubicación(es)',
    col_hours: 'Hrs / mes',
    col_actions: 'Acciones',
    no_volunteers: 'No se encontraron voluntarios',
    no_volunteers_sub: 'Intenta ajustar tu búsqueda o filtros.',
    status_volunteer: 'Voluntario',
    status_prospect: 'Prospecto',
    status_applicant: 'Solicitante',
    status_inactive: 'Inactivo',
    clear: 'Limpiar',
    result: 'resultado',
    results: 'resultados',
    this_mo: 'este mes.',

    // Add volunteer modal
    add_volunteer_title: 'Agregar voluntario',
    add_volunteer_sub: 'Crea una cuenta y perfil de voluntario',
    first_name_required: 'Nombre *',
    last_name_required: 'Apellido *',
    email_address_required: 'Correo electrónico *',
    phone_optional: 'Teléfono',
    optional: 'opcional',
    category_required: 'Categoría *',
    status_required: 'Estado *',
    assign_locations: 'Asignar a ubicación(es)',
    send_invite_email: 'Enviar correo de invitación',
    send_invite_desc: 'El voluntario recibe un enlace para establecer su propia contraseña. Desmarcar para crear la cuenta silenciosamente (deberás compartir las credenciales manualmente).',
    volunteer_added: '¡Voluntario agregado!',
    invite_sent: 'Se ha enviado un correo de invitación.',
    account_created: 'Cuenta creada exitosamente.',
    creating: 'Creando…',
    done: '✓ Listo',
    cancel: 'Cancelar',

    // Volunteer detail — header
    back_to_volunteers: 'Volver a Voluntarios',
    total_hours_label: 'Total de horas',
    credentials_label: 'Credenciales',
    lessons_done_label: 'Lecciones completadas',
    joined: 'Se unió',

    // Volunteer detail — tabs
    tab_info: 'Información',
    tab_onboarding: 'Incorporación',
    tab_credentials: 'Credenciales',
    tab_hours: 'Horas',
    tab_documents: 'Documentos',
    tab_background_check: 'Antecedentes',
    tab_flags: 'Marcadores',
    tab_notes: 'Notas',

    // InfoTab
    volunteer_details: 'Detalles del voluntario',
    edit: 'Editar',
    save: 'Guardar cambios',
    saving: 'Guardando…',
    saved: 'Guardado',
    first_name: 'Nombre',
    last_name: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    status_field: 'Estado',
    emergency_contact: 'Contacto de emergencia',
    emergency_phone: 'Teléfono de emergencia',
    managed_via_pipeline: 'Gestionado en la pestaña de proceso',
    set_by_volunteer: 'Indicado por el voluntario',
    category: 'Categoría',
    categories: 'Categorías',
    select_all_that_apply: 'selecciona todas las que apliquen',
    locations_field: 'Ubicación(es)',

    // Tags
    tags_label: 'Etiquetas',
    add_tag: '+ Agregar etiqueta',
    no_tags_defined: 'No hay etiquetas definidas aún.',
    create_tags_in_settings: 'Crear etiquetas en Configuración →',
    no_tags_applied: 'Sin etiquetas aplicadas.',

    // Notes panel
    add_note_placeholder: 'Agregar una nota…',
    add_note_btn: 'Agregar nota',
    no_notes: 'Sin notas aún.',
    saving_note: 'Guardando…',

    // Documents panel
    upload_document: 'Subir documento',
    drop_files_here: 'Arrastra archivos aquí, o',
    browse: 'explorar',
    drop_files_sub: 'PDF, Word, Excel, PNG, JPG — hasta 50 MB cada uno',
    uploaded_files: 'Archivos subidos',
    signed_documents: 'Documentos firmados',
    supporting_documents: 'Documentos de respaldo',
    no_documents: 'Sin documentos en archivo — sube uno arriba',
    send_via_jotform: 'Enviar vía Jotform',
    form_id: 'ID del formulario',
    send_form: 'Enviar formulario',
    sending: 'Enviando…',
    form_sent: '¡Formulario enviado!',
    open: 'Abrir',

    // Flags panel
    active_flags: 'Marcadores activos',
    raise_flag: 'Agregar marcador',
    no_active_flags: 'Sin marcadores activos.',
    no_flag_types: 'No hay tipos de marcadores definidos aún.',
    create_flags_in_settings: 'Crear marcadores en Configuración →',
    select_flag_type: 'Selecciona un tipo de marcador',
    optional_notes: 'Notas opcionales sobre este marcador…',
    raise_flag_btn: 'Agregar marcador',
    resolve: 'Resolver',
    unresolve: 'Reabrir',
    hide: 'Ocultar',
    show: 'Mostrar',
    resolved: 'resuelto',
    flag: 'marcador',
    flags: 'marcadores',
    raised: 'Levantado',

    // Pipeline phase bar
    pipeline_phase: 'Fase del proceso',
    override: 'Cambiar',
    advance_to: 'Avanzar a',
    final_phase: 'Fase final',

    // Clock in button
    clock_in: 'Registrar entrada',
    clock_out: 'Registrar salida',
    clocking_in: 'Registrando entrada…',
    clocking_out: 'Registrando salida…',
    clocked_in: 'En turno',

    // Onboarding tab
    onboarding_checklist: 'Lista de incorporación',
    complete: 'completo',
    workflow_stages: 'Etapas del flujo',
    stages: 'etapas',
    mark_done: 'Marcar como hecho',
    done_label: 'Hecho',
    pending_label: 'Pendiente',
    no_workflow: 'No hay flujo de incorporación asignado a este voluntario.',
    completed: 'Completado',
    due_within: 'Vence en',
    days_of_start: 'días desde el inicio',

    // Credentials tab
    no_credentials: 'Sin credenciales en archivo',
    license: 'Licencia:',
    expires: 'Vence',
    expired: 'Venció',
    verified: '✓ Verificado',
    days_left: 'd restantes',

    // Hours tab
    total_hours: 'Total de horas',
    sessions: 'Sesiones',
    avg_session: 'Sesión promedio',
    no_time_entries: 'Sin registros de tiempo aún',
    date: 'Fecha',
    location: 'Ubicación',
    clock_in_col: 'Entrada',
    clock_out_col: 'Salida',
    duration: 'Duración',
    method: 'Método',
    active_label: 'Activo',

    // Background check tab
    no_bg_check: 'No se ha iniciado una verificación de antecedentes',
    initiate_bg_check: 'Iniciar verificación de antecedentes',
    provider: 'Proveedor',
    bg_status: 'Estado',
    initiated: 'Iniciado',
    bg_completed: 'Completado',
    bg_result: 'Resultado',

    // Shifts
    shifts_title: 'Turnos',
    new_shift: 'Nuevo turno',
    no_shifts: 'Sin turnos',
    shift_date: 'Fecha',
    shift_time: 'Hora',
    shift_location: 'Ubicación',
    shift_volunteer: 'Voluntario',
    shift_status: 'Estado',
    week_view: 'Semana',
    day_view: 'Día',
    list_view: 'Lista',
    month_view: 'Mes',
    today: 'Hoy',
    upcoming: 'Próximos',
    past: 'Anteriores',
    shift_name: 'Nombre del turno',
    start_date: 'Fecha de inicio',
    start_time: 'Hora de inicio',
    end_date: 'Fecha de fin',
    end_date_occurrence: 'Cada turno termina el',
    end_time: 'Hora de fin',
    end_time_occurrence: 'Cada turno termina a las',
    required_volunteers: 'Voluntarios requeridos',
    shift_notes: 'Notas',
    assign_volunteers: 'Asignar voluntarios',
    assign_btn: 'Asignar',
    create_shift: 'Crear turno',
    delete_shift: 'Eliminar turno',
    edit_shift: 'Editar',
    recurring_shift: 'Turno recurrente',
    repeat_frequency: 'Repetir',
    end_date_optional: 'Fecha de fin de la serie (opcional)',
    series_end_date_hint: 'Dejar en blanco para repetir indefinidamente',
    weekly: 'Semanal',
    biweekly: 'Quincenal',
    monthly: 'Mensual',
    spots_open: 'lugares disponibles',
    spot_open: 'lugar disponible',
    no_shifts_this_day: 'Sin turnos este día.',
    no_results: 'Sin resultados',
    search_volunteers: 'Buscar voluntarios…',
    select_mentor: 'Selecciona un mentor para',
    trainee_label: 'Aprendiz',
    no_eligible_mentors: 'No se encontraron mentores elegibles.',

    // Edit recurring modal
    edit_recurring_title: 'Editar turno recurrente',
    this_shift_only: 'Solo este turno',
    this_shift_only_desc: 'Solo se actualizará la ocurrencia seleccionada.',
    this_and_future: 'Este y todos los turnos futuros',
    this_and_future_desc: 'Este y todas las ocurrencias posteriores se actualizarán.',
    confirm: 'Confirmar',

    // Documents view
    documents_title: 'Documentos',
    no_documents_found: 'No se encontraron documentos',
    preset_docs: 'Formularios estándar',
    volunteer_repo: 'Repositorio de voluntarios',
    internal_docs: 'Documentos internos',
    upload_file: 'Subir archivo',
    hidden: 'Oculto',
    visible: 'Visible',
    preset: 'Predefinido',
    internal: 'Interno',
    standard_form: 'Formulario estándar · Siempre visible para voluntarios',

    // Reports
    reports_title: 'Informes',
    total_volunteers: 'Total de voluntarios',
    total_hours_report: 'Total de horas',
    active_volunteers: 'Voluntarios activos',
    hours_this_month: 'Horas este mes',
    hours_tab: 'Horas',
    onboarding_tab: 'Incorporación',
    bgchecks_tab: 'Antecedentes',
    credentials_tab: 'Vencimiento de credenciales',
    inactive_tab: 'Inactivos',
    filters: 'Filtros',
    apply: 'Aplicar',
    status_filter: 'Estado',
    category_filter: 'Categoría',
    pipeline_phase_filter: 'Fase del proceso',
    joined_from: 'Se unió desde',
    joined_to: 'Se unió hasta',
    all: 'Todos',
    export_csv: 'Exportar CSV',
    mark_inactive: 'Marcar como inactivo',
    approve: 'Aprobar',
    reject: 'Rechazar',
    color: 'Color',
    add_tag_btn: 'Agregar etiqueta',
    pending_hour_approvals: 'Aprobaciones de horas pendientes',
    no_pending_hours: 'No hay horas pendientes para revisar.',
    volunteer: 'Voluntario',
    shift_hours: 'Horas',
    sessions_col: 'Sesiones',
    distribution_col: 'Distribución',
    no_hours_found: 'No se encontraron datos de horas',
    all_phases: 'Todas las fases',
    no_volunteers_filter: 'Ningún voluntario coincide con el filtro actual',
    phase_col: 'Fase',
    workflow_col: 'Flujo',
    stages_col: 'Etapas',
    progress_col: 'Progreso',
    no_workflow_assigned: 'Sin flujo',
    no_bgcheck_data: 'Sin datos de antecedentes aún',
    custom_days: 'Personalizado',
    set_day_threshold: 'Establece un umbral de días arriba',
    no_inactive_volunteers: 'Sin voluntarios inactivos por',
    name_col: 'Nombre',
    last_active_col: 'Última actividad',
    no_activity_in_last: 'Sin actividad en los últimos:',
    days_suffix: 'días',
    expiring_within: 'Vence en:',
    no_creds_expiring: 'Sin credenciales que venzan en los próximos',
    days_label: 'días',
    marking_inactive: 'Marcando…',
    credential_type_col: 'Tipo de credencial',
    expires_col: 'Vence',
    days_left_col: 'Días restantes',
    urgency_col: 'Urgencia',
    never_label: 'Nunca',

    // Messages
    messages_title: 'Mensajes',
    send_message: 'Enviar mensaje',
    message_placeholder: 'Escribe un mensaje…',
    compose: 'Redactar',
    compose_new_message: 'Redactar nuevo mensaje',
    inbox: 'Bandeja de entrada',
    all_volunteers: 'Todos los voluntarios',
    group_by_category: 'Por categoría',
    individual: 'Individual',
    by_category_label: 'Por categoría',
    individuals_label: 'Individuales',
    subject: 'Asunto',
    body: 'Mensaje',
    send: 'Enviar',
    sending_msg: 'Enviando…',
    send_later: 'Enviar después',
    schedule_for: 'Programado para',
    scheduled_badge: 'Programado',
    cancel_schedule: 'Enviar ahora en su lugar',
    recipient_count: 'destinatario',
    recipient_count_plural: 'destinatarios',
    save_template: 'Guardar como plantilla',
    templates: 'Plantillas',
    no_messages: 'No se han enviado mensajes aún.',
    no_messages_hint: 'Redacta un mensaje para comenzar',
    no_templates_yet: 'Sin plantillas aún. Redacta un mensaje y guárdalo como plantilla.',
    use_template: 'Usar',
    select_template_placeholder: 'Seleccionar una plantilla…',
    template_name_label: 'Nombre de plantilla',
    channel_label: 'Canal',
    to_label: 'Para',
    channel_email: 'Correo',
    channel_sms: 'SMS',
    channel_push: 'Notificación',
    new_message: 'Nuevo mensaje',
    message_body_label: 'Cuerpo del mensaje',
    select_message_view: 'Selecciona un mensaje para ver',
    recipients_stat: 'Destinatarios',
    delivered_stat: 'Entregados',
    read_stat: 'Leídos',
    sent_prefix: 'Enviado',
    save_label: 'Guardar',

    // Alerts
    alerts_title: 'Alertas',
    no_alerts: 'Sin alertas aún',
    no_alerts_sub: 'Las alertas aparecerán aquí cuando se activen las reglas de automatización de documentos.',
    mark_resolved: 'Marcar como resuelto',
    mark_all_read: 'Marcar todo como leído',
    alert_type: 'Tipo',
    alert_message: 'Mensaje',
    unread: 'no leída',
    view_volunteer: 'Ver voluntario →',

    // Settings
    settings_title: 'Configuración',
    categories_section: 'Categorías',
    add_category: 'Agregar categoría',
    category_name: 'Nombre de categoría',
    archive: 'Archivar',
    restore: 'Restaurar',
    tags_section: 'Etiquetas',
    flags_section: 'Marcadores',
    tags_desc: 'Etiquetas categóricas aplicadas a voluntarios para agrupar y filtrar.',
    flags_desc: 'Marcadores de alerta para problemas que requieren atención (ej. "Referencia sin llamar", "Licencia por vencer").',
    no_tags_yet: 'Sin etiquetas aún.',
    no_flags_yet: 'Sin marcadores definidos aún.',
    tag_name: 'Nombre de etiqueta',
    create_tag: 'Crear etiqueta',
    flag_name: 'Nombre del marcador',
    flag_description: 'Descripción (opcional)',
    severity: 'Severidad',
    severity_info: 'Info',
    severity_warning: 'Advertencia',
    severity_critical: 'Crítico',
    add_flag_btn: 'Agregar marcador',
    create_flag: 'Crear marcador',
    org_profile: '🏢 Perfil de organización',
    locations_tab: '📍 Ubicaciones',
    integrations_tab: '🔗 Integraciones',
    categories_tab: '🗂 Categorías',
    holidays_tab: '📅 Días festivos',
    automation_tab: '⚡ Automatización',
    tags_tab: '🏷 Etiquetas',
    flags_tab: '🚩 Marcadores',

    // Learning
    learning_title: 'Aprendizaje',
    new_module: 'Nuevo módulo',
    lessons: 'Lecciones',
    completions: 'Completadas',
    add_lesson: 'Agregar lección',
    no_modules: 'Sin módulos aún.',
    module_title: 'Título del módulo',
    lesson_title: 'Título de la lección',
    lesson_type: 'Tipo',
    save_module: 'Guardar módulo',
  },
}

// ── Contexts ──────────────────────────────────────────────────────────────────
export const AdminLangContext = createContext<AdminLang>('en')
export const AdminSetLangContext = createContext<(l: AdminLang) => void>(() => {})

// ── Provider ──────────────────────────────────────────────────────────────────
export function AdminLangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<AdminLang>('en')

  // Read from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem('admin-lang')
    if (stored === 'es') setLangState('es')
  }, [])

  function setLang(l: AdminLang) {
    setLangState(l)
    localStorage.setItem('admin-lang', l)
  }

  return (
    <AdminSetLangContext.Provider value={setLang}>
      <AdminLangContext.Provider value={lang}>
        {children}
      </AdminLangContext.Provider>
    </AdminSetLangContext.Provider>
  )
}

// ── Hook ──────────────────────────────────────────────────────────────────────
export function useAdminT() {
  const lang = useContext(AdminLangContext)
  return (key: string): string =>
    ADMIN_TRANSLATIONS[lang]?.[key] ?? ADMIN_TRANSLATIONS.en[key] ?? key
}
